[package]
edition = "2024"
name    = "swc_experimental_ecma_visit"
version = "0.1.0"

[dependencies]
swc_common = { workspace = true }

swc_experimental_ecma_ast = { workspace = true }

[dev-dependencies]
swc_experimental_ecma_parser = { workspace = true }
